#!/bin/bash -l

# Enable nbgitpuller
jupyter server extension enable --sys-prefix nbgitpuller

# Update Jupyter Lab Configuration
mkdir -p /srv/conda/envs/notebook/share/jupyter/lab/settings
cp -u overrides.json /srv/conda/envs/notebook/share/jupyter/lab/settings
