#!/bin/bash

rm -rf ~/.jupyter
jupyter-lab --generate-config
cd ~/.jupyter
curl -o jupyter_lab_config.py https://raw.githubusercontent.com/ccsf-math/jupyterhub/main/nbconvert_config.py
cd ~

exec "$@"
